
g = MGU_granary(s, 0, 8);
g.readFile("/Users/pchdev/Desktop/_mix/Unknown Album/03. Spherical field.wav");
g.readFile();
g.rate;
g.rate = [1, 2.1, 2, 0.5, 1.5, 1, 1, 0.5];
g.rate = [1, 3, 1, 1, 1.5, 1, 2, 1];
g.rate = [1, 1, 1, 1, 1.5, 1, 1, 1];
g.rate = 0.8;
g.rate = 0.9;
g.rate = 1.3;
g.amp = 1;

(
g.startPos = 0.7;
g.stopPos = g.startPos + 0.0005;
)

g.grainSize = 75;
g.play;
g.stop;
g.rate = 1.2;
g.rdmCoeff = 1000;
g.rdmCoeff = 10;
g.rdmCoeff = 100;
g.rdmCoeff = 200;
g.panWidth = 0.1;
g.panWidth = 1;